# Curated tech skills database.
# Structure: canonical display name → [plain-text match variants, all lowercase].
# NO regex markers here — extractor.py re.escapes everything and adds word boundaries.
# Variants are sorted longest-first within each entry; the extractor also global-sorts,
# so "node.js" is always tried before "node", "spring boot" before "spring", etc.

SKILL_VARIANTS: dict[str, list[str]] = {

    # ── Languages ──────────────────────────────────────────────────────────────
    "Python":               ["python"],
    "JavaScript":           ["javascript", "ecmascript", "js"],
    "TypeScript":           ["typescript", "ts"],
    "Java":                 ["java"],
    "C++":                  ["c/c++", "c++", "cpp"],
    "C#":                   ["c sharp", "csharp", "c#"],
    "Go":                   ["golang", "go"],
    "Rust":                 ["rust"],
    "Ruby":                 ["ruby"],
    "PHP":                  ["php"],
    "Swift":                ["swift"],
    "Kotlin":               ["kotlin"],
    "Scala":                ["scala"],
    "R":                    ["r"],
    "MATLAB":               ["matlab"],
    "Perl":                 ["perl"],
    "Bash":                 ["shell scripting", "bash"],
    "PowerShell":           ["powershell"],
    "Lua":                  ["lua"],
    "Haskell":              ["haskell"],
    "Elixir":               ["elixir"],
    "Clojure":              ["clojure"],
    "Dart":                 ["dart"],
    "Groovy":               ["groovy"],
    "Solidity":             ["solidity"],
    "COBOL":                ["cobol"],

    # ── Frontend Frameworks ────────────────────────────────────────────────────
    "React":                ["react.js", "reactjs", "react"],
    "Vue":                  ["vue.js", "vuejs", "vue"],
    "Angular":              ["angularjs", "angular.js", "angular"],
    "Svelte":               ["svelte"],
    "Next.js":              ["next.js", "nextjs"],
    "Nuxt":                 ["nuxt.js", "nuxtjs", "nuxt"],
    "Gatsby":               ["gatsby"],
    "Remix":                ["remix"],
    "Ember":                ["ember.js", "ember"],
    "Backbone.js":          ["backbone.js", "backbone"],
    "jQuery":               ["jquery"],
    "Alpine.js":            ["alpine.js", "alpinejs"],
    "Astro":                ["astro"],
    "SolidJS":              ["solid.js", "solidjs"],
    "Qwik":                 ["qwik"],

    # ── State Management ──────────────────────────────────────────────────────
    "Redux":                ["redux toolkit", "redux"],
    "Zustand":              ["zustand"],
    "MobX":                 ["mobx"],
    "Recoil":               ["recoil"],
    "Jotai":                ["jotai"],
    "React Query":          ["react query", "tanstack query"],
    "SWR":                  ["swr"],
    "Pinia":                ["pinia"],
    "Vuex":                 ["vuex"],
    "NgRx":                 ["ngrx"],

    # ── Build Tools / Bundlers ─────────────────────────────────────────────────
    "Webpack":              ["webpack"],
    "Vite":                 ["vite"],
    "esbuild":              ["esbuild"],
    "Parcel":               ["parcel"],
    "Rollup":               ["rollup"],
    "Turbopack":            ["turbopack"],
    "Babel":                ["babel"],
    "ESLint":               ["eslint"],
    "Prettier":             ["prettier"],

    # ── CSS / Styling ──────────────────────────────────────────────────────────
    "CSS":                  ["css3", "css"],
    "HTML":                 ["html5", "html"],
    "Tailwind CSS":         ["tailwindcss", "tailwind css", "tailwind"],
    "Bootstrap":            ["bootstrap"],
    "Material UI":          ["material-ui", "material ui", "mui"],
    "Sass":                 ["scss", "sass"],
    "CSS Modules":          ["css modules"],
    "styled-components":    ["styled-components", "styled components"],
    "Less":                 ["less"],
    "Chakra UI":            ["chakra ui", "chakra"],
    "Ant Design":           ["ant design", "antd"],
    "Radix UI":             ["radix ui", "radix"],
    "shadcn/ui":            ["shadcn/ui", "shadcn"],

    # ── Backend Frameworks ─────────────────────────────────────────────────────
    "Node.js":              ["node.js", "nodejs", "node"],
    "Express":              ["express.js", "expressjs", "express"],
    "NestJS":               ["nest.js", "nestjs"],
    "Django":               ["django"],
    "Flask":                ["flask"],
    "FastAPI":              ["fastapi"],
    "Spring Boot":          ["spring boot"],
    "Spring":               ["spring framework", "spring"],
    "Ruby on Rails":        ["ruby on rails", "rails", "ror"],
    "Laravel":              ["laravel"],
    "Symfony":              ["symfony"],
    "ASP.NET Core":         ["asp.net core"],
    "ASP.NET":              ["asp.net", "aspnet"],
    ".NET":                 [".net", "dotnet"],
    "Phoenix":              ["phoenix framework", "phoenix"],
    "Gin":                  ["gin"],
    "Fiber":                ["fiber"],
    "Actix":                ["actix"],
    "Koa":                  ["koa.js", "koa"],
    "Fastify":              ["fastify"],
    "Hapi":                 ["hapi.js", "hapi"],
    "Tornado":              ["tornado"],
    "Celery":               ["celery"],
    "tRPC":                 ["trpc"],

    # ── Databases ─────────────────────────────────────────────────────────────
    "PostgreSQL":           ["postgresql", "postgres"],
    "MySQL":                ["mysql"],
    "MongoDB":              ["mongodb", "mongo"],
    "Redis":                ["redis"],
    "Cassandra":            ["apache cassandra", "cassandra"],
    "DynamoDB":             ["dynamodb"],
    "SQLite":               ["sqlite"],
    "Oracle DB":            ["oracle database", "oracle db", "oracle"],
    "SQL Server":           ["microsoft sql server", "sql server", "mssql"],
    "MariaDB":              ["mariadb"],
    "Elasticsearch":        ["elasticsearch", "elastic search"],
    "CouchDB":              ["couchdb"],
    "Neo4j":                ["neo4j"],
    "InfluxDB":             ["influxdb"],
    "Firestore":            ["cloud firestore", "firestore"],
    "Supabase":             ["supabase"],
    "CockroachDB":          ["cockroachdb"],
    "PlanetScale":          ["planetscale"],
    "Pinecone":             ["pinecone"],
    "Weaviate":             ["weaviate"],
    "Chroma":               ["chromadb", "chroma"],
    "SQL":                  ["sql"],
    "NoSQL":                ["nosql"],

    # ── Cloud Platforms ────────────────────────────────────────────────────────
    "AWS":                  ["amazon web services", "aws"],
    "Azure":                ["microsoft azure", "azure"],
    "GCP":                  ["google cloud platform", "google cloud", "gcp"],
    "Firebase":             ["firebase"],
    "Vercel":               ["vercel"],
    "Netlify":              ["netlify"],
    "Heroku":               ["heroku"],
    "DigitalOcean":         ["digitalocean", "digital ocean"],
    "Cloudflare":           ["cloudflare"],

    # ── AWS Services ──────────────────────────────────────────────────────────
    "EC2":                  ["ec2"],
    "S3":                   ["s3"],
    "AWS Lambda":           ["aws lambda"],
    "Lambda":               ["lambda"],
    "RDS":                  ["rds"],
    "ECS":                  ["ecs"],
    "EKS":                  ["eks"],
    "CloudFront":           ["cloudfront"],
    "SQS":                  ["sqs"],
    "SNS":                  ["sns"],
    "API Gateway":          ["api gateway"],
    "CloudWatch":           ["cloudwatch"],
    "Cognito":              ["aws cognito", "cognito"],
    "IAM":                  ["iam"],
    "Redshift":             ["amazon redshift", "redshift"],
    "Athena":               ["aws athena", "athena"],
    "Kinesis":              ["aws kinesis", "kinesis"],
    "SageMaker":            ["amazon sagemaker", "sagemaker"],
    "Bedrock":              ["amazon bedrock", "bedrock"],

    # ── DevOps / Infrastructure ────────────────────────────────────────────────
    "Docker":               ["docker"],
    "Kubernetes":           ["kubernetes", "k8s"],
    "Terraform":            ["terraform"],
    "Ansible":              ["ansible"],
    "Jenkins":              ["jenkins"],
    "GitHub Actions":       ["github actions"],
    "GitLab CI/CD":         ["gitlab ci/cd", "gitlab ci"],
    "CircleCI":             ["circleci"],
    "Travis CI":            ["travis ci"],
    "ArgoCD":               ["argo cd", "argocd"],
    "Helm":                 ["helm"],
    "Prometheus":           ["prometheus"],
    "Grafana":              ["grafana"],
    "Nginx":                ["nginx"],
    "HAProxy":              ["haproxy"],
    "Pulumi":               ["pulumi"],
    "CDK":                  ["aws cdk", "cdk"],
    "Vagrant":              ["vagrant"],
    "Puppet":               ["puppet"],
    "Chef":                 ["chef"],
    "Packer":               ["packer"],
    "Vault":                ["hashicorp vault", "vault"],
    "Consul":               ["hashicorp consul", "consul"],

    # ── APIs / Protocols ──────────────────────────────────────────────────────
    "REST API":             ["restful api", "rest api", "restful", "rest"],
    "GraphQL":              ["graphql"],
    "gRPC":                 ["grpc"],
    "WebSockets":           ["websockets", "websocket"],
    "OAuth":                ["oauth 2.0", "oauth2", "oauth"],
    "JWT":                  ["json web token", "jwt"],
    "OpenAPI":              ["openapi", "swagger"],
    "Webhook":              ["webhooks", "webhook"],
    "WebRTC":               ["webrtc"],
    "MQTT":                 ["mqtt"],

    # ── Message Queues / Streaming ─────────────────────────────────────────────
    "Apache Kafka":         ["apache kafka", "kafka"],
    "RabbitMQ":             ["rabbitmq"],
    "Apache Pulsar":        ["apache pulsar", "pulsar"],
    "BullMQ":               ["bullmq", "bull"],

    # ── ML / AI / Data Science ─────────────────────────────────────────────────
    "TensorFlow":           ["tensorflow", "tf"],
    "PyTorch":              ["pytorch"],
    "scikit-learn":         ["scikit-learn", "scikit learn", "sklearn"],
    "Keras":                ["keras"],
    "Pandas":               ["pandas"],
    "NumPy":                ["numpy"],
    "Matplotlib":           ["matplotlib"],
    "Seaborn":              ["seaborn"],
    "Plotly":               ["plotly"],
    "NLTK":                 ["nltk"],
    "spaCy":                ["spacy"],
    "Hugging Face":         ["hugging face", "huggingface"],
    "LangChain":            ["langchain"],
    "LlamaIndex":           ["llamaindex", "llama index"],
    "OpenAI API":           ["openai api", "openai"],
    "Machine Learning":     ["machine learning"],
    "Deep Learning":        ["deep learning"],
    "NLP":                  ["natural language processing", "nlp"],
    "Computer Vision":      ["computer vision"],
    "Reinforcement Learning": ["reinforcement learning"],
    "MLflow":               ["mlflow"],
    "Apache Airflow":       ["apache airflow", "airflow"],
    "Apache Spark":         ["apache spark", "pyspark", "spark"],
    "Hadoop":               ["hadoop"],
    "Apache Flink":         ["apache flink", "flink"],
    "dbt":                  ["dbt"],
    "Snowflake":            ["snowflake"],
    "BigQuery":             ["bigquery"],
    "Databricks":           ["databricks"],
    "Jupyter":              ["jupyter notebook", "jupyter lab", "jupyter"],
    "XGBoost":              ["xgboost"],
    "LightGBM":             ["lightgbm"],
    "Weights & Biases":     ["weights & biases", "wandb"],

    # ── Testing ────────────────────────────────────────────────────────────────
    "Jest":                 ["jest"],
    "Pytest":               ["pytest"],
    "Cypress":              ["cypress"],
    "Selenium":             ["selenium"],
    "Playwright":           ["playwright"],
    "JUnit":                ["junit"],
    "Mocha":                ["mocha"],
    "Vitest":               ["vitest"],
    "React Testing Library": ["react testing library", "testing library"],
    "Storybook":            ["storybook"],
    "Postman":              ["postman"],
    "k6":                   ["k6"],
    "Locust":               ["locust"],

    # ── Data Formats / Serialization ──────────────────────────────────────────
    "JSON":                 ["json"],
    "XML":                  ["xml"],
    "YAML":                 ["yaml"],
    "Protobuf":             ["protocol buffers", "protobuf"],
    "Avro":                 ["avro"],
    "Parquet":              ["parquet"],

    # ── Version Control / Collaboration ───────────────────────────────────────
    "Git":                  ["git"],
    "GitHub":               ["github"],
    "GitLab":               ["gitlab"],
    "Bitbucket":            ["bitbucket"],
    "Jira":                 ["jira"],
    "Confluence":           ["confluence"],
    "Figma":                ["figma"],

    # ── Mobile ────────────────────────────────────────────────────────────────
    "React Native":         ["react native"],
    "Flutter":              ["flutter"],
    "Expo":                 ["expo"],
    "Android":              ["android"],
    "iOS":                  ["ios"],
    "Xcode":                ["xcode"],

    # ── Security ──────────────────────────────────────────────────────────────
    "SSL/TLS":              ["ssl/tls", "tls", "ssl"],
    "OWASP":                ["owasp"],
    "Penetration Testing":  ["penetration testing", "pen testing", "pentest"],

    # ── Observability / Monitoring ─────────────────────────────────────────────
    "Datadog":              ["datadog"],
    "New Relic":            ["new relic"],
    "Sentry":               ["sentry"],
    "OpenTelemetry":        ["opentelemetry"],
    "Splunk":               ["splunk"],
    "ELK Stack":            ["elk stack", "elk"],
    "Logstash":             ["logstash"],
    "Kibana":               ["kibana"],
    "Jaeger":               ["jaeger"],

    # ── Concepts / Practices ──────────────────────────────────────────────────
    "Microservices":        ["microservice architecture", "microservices"],
    "CI/CD":                ["continuous deployment", "continuous delivery", "continuous integration", "ci/cd"],
    "Agile":                ["agile methodology", "scrum", "agile"],
    "TDD":                  ["test-driven development", "test driven development", "tdd"],
    "BDD":                  ["behavior-driven development", "bdd"],
    "DevOps":               ["devops"],
    "Serverless":           ["serverless"],
    "Event-Driven":         ["event-driven architecture", "event driven"],
    "Domain-Driven Design": ["domain-driven design", "domain driven design", "ddd"],
    "System Design":        ["system design"],
    "Distributed Systems":  ["distributed systems"],
    "OOP":                  ["object-oriented programming", "object oriented programming", "oop"],
    "Functional Programming": ["functional programming"],
    "Design Patterns":      ["design patterns"],
    "Data Structures":      ["data structures"],
    "Algorithms":           ["algorithms"],
    "API Design":           ["api design"],
    "Code Review":          ["code review"],
}

# Flat map: lowercase_variant → canonical display name.
# Used for O(1) lookup after a regex match returns plain matched text.
ALIAS_MAP: dict[str, str] = {}
for _canonical, _variants in SKILL_VARIANTS.items():
    for _v in _variants:
        ALIAS_MAP[_v.lower()] = _canonical
